# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.CharField(max_length=10)),
                ('payment_type', models.CharField(blank=True, max_length=10, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=30, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipts.Patient')),
            ],
        ),
    ]
