# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='status',
            field=models.CharField(default='Not Completed', max_length=25),
        ),
    ]
